name = "costella-telchac-residencial"
compatibility_date = "2026-09-30"
workers_dev = true

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "costella-leads"
database_id = "00000000-00000006-000050fd-e4bfea5cbd11a1a92edac5d4413eba31"

[vars]
ADMIN_KEY = "COSTELLA-ADMIN-2026"
